import * as P from '@react-pdf/primitives';

export enum Primitive {
  G = P.G,
  Svg = P.Svg,
  View = P.View,
  Text = P.Text,
  Link = P.Link,
  Page = P.Page,
  Note = P.Note,
  Path = P.Path,
  Rect = P.Rect,
  Line = P.Line,
  Stop = P.Stop,
  Defs = P.Defs,
  Image = P.Image,
  Tspan = P.Tspan,
  Canvas = P.Canvas,
  Circle = P.Circle,
  Ellipse = P.Ellipse,
  Polygon = P.Polygon,
  Document = P.Document,
  Polyline = P.Polyline,
  ClipPath = P.ClipPath,
  TextInstance = P.TextInstance,
  LinearGradient = P.LinearGradient,
  RadialGradient = P.RadialGradient,
}
