export enum Primitive {
  G = 'G',
  Svg = 'SVG',
  View = 'VIEW',
  Text = 'TEXT',
  Link = 'LINK',
  Page = 'PAGE',
  Note = 'NOTE',
  Path = 'PATH',
  Rect = 'RECT',
  Line = 'LINE',
  Stop = 'STOP',
  Defs = 'DEFS',
  Image = 'IMAGE',
  Tspan = 'TSPAN',
  Canvas = 'CANVAS',
  Circle = 'CIRCLE',
  Ellipse = 'ELLIPSE',
  Polygon = 'POLYGON',
  Document = 'DOCUMENT',
  Polyline = 'POLYLINE',
  ClipPath = 'CLIP_PATH',
  TextInstance = 'TEXT_INSTANCE',
  LinearGradient = 'LINEAR_GRADIENT',
  RadialGradient = 'RADIAL_GRADIENT',
}
