import type {
  CompletionContext,
  CompletionResult,
} from '@codemirror/autocomplete';

const COMPONENTS = [
  'Document',
  'Page',
  'View',
  'Text',
  'Link',
  'Image',
  'Note',
  'Canvas',
  'Svg',
  'Line',
  'Polyline',
  'Polygon',
  'Path',
  'Rect',
  'Circle',
  'Ellipse',
  'Tspan',
  'G',
  'Stop',
  'Defs',
  'ClipPath',
  'LinearGradient',
  'RadialGradient',
  'TextInput',
  'Checkbox',
  'Select',
  'FieldSet',
  'PDFViewer',
  'PDFDownloadLink',
  'BlobProvider',
  'StyleSheet',
  'Font',
  'pdf',
];

const PROPS = [
  'style',
  'fixed',
  'break',
  'wrap',
  'debug',
  'render',
  'src',
  'source',
  'size',
  'orientation',
  'dpi',
  'bookmark',
  'cache',
  'minPresenceAhead',
  'hyphenationCallback',
  'orphans',
  'widows',
];

// ponytail: curated list; regenerate from @react-pdf/stylesheet's Style type if it grows
const STYLE_KEYS = [
  'alignContent',
  'alignItems',
  'alignSelf',
  'aspectRatio',
  'backgroundColor',
  'border',
  'borderBottom',
  'borderBottomColor',
  'borderBottomLeftRadius',
  'borderBottomRightRadius',
  'borderBottomStyle',
  'borderBottomWidth',
  'borderColor',
  'borderLeft',
  'borderLeftColor',
  'borderLeftStyle',
  'borderLeftWidth',
  'borderRadius',
  'borderRight',
  'borderRightColor',
  'borderRightStyle',
  'borderRightWidth',
  'borderStyle',
  'borderTop',
  'borderTopColor',
  'borderTopLeftRadius',
  'borderTopRightRadius',
  'borderTopStyle',
  'borderTopWidth',
  'borderWidth',
  'bottom',
  'clear',
  'clipPath',
  'color',
  'columnGap',
  'direction',
  'display',
  'dominantBaseline',
  'fill',
  'fillOpacity',
  'fillRule',
  'flex',
  'flexBasis',
  'flexDirection',
  'flexFlow',
  'flexGrow',
  'flexShrink',
  'flexWrap',
  'float',
  'fontFamily',
  'fontFeatureSettings',
  'fontSize',
  'fontStyle',
  'fontWeight',
  'gap',
  'gradientTransform',
  'height',
  'justifyContent',
  'justifySelf',
  'left',
  'letterSpacing',
  'lineHeight',
  'margin',
  'marginBottom',
  'marginHorizontal',
  'marginLeft',
  'marginRight',
  'marginTop',
  'marginVertical',
  'maxHeight',
  'maxLines',
  'maxWidth',
  'minHeight',
  'minWidth',
  'objectFit',
  'objectPosition',
  'opacity',
  'overflow',
  'padding',
  'paddingBottom',
  'paddingHorizontal',
  'paddingLeft',
  'paddingRight',
  'paddingTop',
  'paddingVertical',
  'position',
  'remBase',
  'right',
  'rowGap',
  'shapeOutside',
  'stroke',
  'strokeDasharray',
  'strokeLinecap',
  'strokeLinejoin',
  'strokeOpacity',
  'strokeWidth',
  'textAlign',
  'textAnchor',
  'textDecoration',
  'textDecorationColor',
  'textDecorationStyle',
  'textIndent',
  'textOverflow',
  'textTransform',
  'top',
  'transform',
  'transformOrigin',
  'verticalAlign',
  'visibility',
  'width',
  'zIndex',
];

const toOptions = (words: string[], type: string) =>
  words.map((label) => ({ label, type }));

export function reactPdfCompletions(
  context: CompletionContext,
): CompletionResult | null {
  const word = context.matchBefore(/[\w-]*/);
  if (!word || (word.from === word.to && !context.explicit)) return null;

  const before = context.state.sliceDoc(Math.max(0, word.from - 30), word.from);
  const inJsxTag = /<\/?\s*$/.test(before);
  const inStyleObject =
    /[{,]\s*$/.test(before) &&
    /style|Style/.test(
      context.state.sliceDoc(Math.max(0, word.from - 200), word.from),
    );

  const options = inJsxTag
    ? toOptions(COMPONENTS, 'class')
    : inStyleObject
      ? toOptions(STYLE_KEYS, 'property')
      : [...toOptions(COMPONENTS, 'class'), ...toOptions(PROPS, 'property')];

  return { from: word.from, options, validFor: /^[\w-]*$/ };
}
