name: Site

on:
  pull_request:
    paths:
      - 'apps/site/**'
      - '.github/workflows/site.yml'
  push:
    branches:
      - master
    paths:
      - 'apps/site/**'
      - '.github/workflows/site.yml'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  FORCE_COLOR: 2
  HUSKY: 0
  NODE_VERSION: 22

defaults:
  run:
    working-directory: apps/site

jobs:
  build:
    name: Test and build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Cache Yarn cache
        uses: actions/cache@v4
        env:
          cache-name: yarn-cache-site
        with:
          path: ~/.cache/yarn
          key: ${{ runner.os }}-${{ env.cache-name }}-${{ hashFiles('apps/site/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-${{ env.cache-name }}-

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: Install dependencies
        run: yarn install --frozen-lockfile

      - name: Run tests
        run: yarn test

      - name: Typecheck
        run: npx tsc --noEmit

      - name: Build
        run: yarn build
